version: '3'

services:

  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - D:\0.01 - PROJETS\2.02 - HUGO\src:/src
  server:
    image: klakegg/hugo:0.78.2
    command: server
    volumes:
      - D:\0.01 - PROJETS\2.02 - HUGO\src:/src
    ports:
      - "1313:1313"
    entrypoint: hugo server -D --disableFastRender --renderToDisk -w --noHTTPCache