version: '3'

services:
       
    postgresql:
        image: postgres:alpine
        env_file: ./docker/postgres.env
        ports: 
            - "5432:5432"
        volumes:
            - D:\0.02 - DOCKER\postgresql\data:/var/lib/postgresql/data