version: '3'

services:
       
    php55:

        build:
            context: ./
            dockerfile: Dockerfile
        
        ports:
          - "82:80"
        volumes:
            - D:\0.01 - PROJETS:/var/www/PROJETS
